# Generated by Django 6.0.3 on 2026-03-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sw', models.CharField(max_length=150)),
                ('topic_en', models.CharField(max_length=150)),
                ('description_sw', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='consultations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmManagementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name_sw', models.CharField(max_length=100)),
                ('service_name_en', models.CharField(max_length=100)),
                ('description_sw', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sw', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_sw', models.TextField()),
                ('description_en', models.TextField()),
                ('usage_time_sw', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_time_en', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fertilizers/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sw', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description_sw', models.TextField()),
                ('description_en', models.TextField()),
                ('usage_time_sw', models.CharField(max_length=200)),
                ('usage_time_en', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='seeds/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='glagroapp.expertconsultation')),
            ],
        ),
        migrations.CreateModel(
            name='FarmServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='glagroapp.farmmanagementservice')),
            ],
        ),
        migrations.CreateModel(
            name='FarmServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('before_description', models.TextField()),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='farm_reports/before/')),
                ('after_description', models.TextField()),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='farm_reports/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='glagroapp.farmmanagementservice')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='glagroapp.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='SeedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='glagroapp.seed')),
            ],
        ),
    ]
