# Generated by Django 6.0.3 on 2026-03-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_testimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
