# Generated by Django 6.0.3 on 2026-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationorder',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='farmserviceorder',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='fertilizerorder',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='seedorder',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=20),
        ),
    ]
